---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: chronos
description: This is my personal OS image.

base-image: ghcr.io/wayblueorg/hyprland-nvidia
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
    install:
      - ghostty
      - starship
      - nano
      - vi
    remove:
      - firefox
      - firefox-langpacks

  - type: default-flatpaks
    configurations:
      - notify: true
        scope: user
        install:
          - io.github.kolunmi.Bazaar
          - app.zen_browser.zen
          - org.remmina.Remmina
          - dev.zed.Zed
          - com.getpostman.Postman
          - io.github.dvlv.boxbuddyrs
          - com.usebottles.bottles
          - it.mijorus.gearlever
        remove:
          - io.github.input_leap.input-leap

  - type: script
    scripts:
      - install_catppucin_theme.sh 
      - install_catppucin_cursor.sh 
      - install_catppucin_icons.sh

  - type: brew
    nofile-limits: true
    brew-analytics: false

  - type: signing

