name: Cleanup GHCR Images

on:
    # every sunday at 00:00
    schedule:
        - cron: '0 0 * * SUN'
    # or manually
    workflow_dispatch:

jobs:
    cleanup:
        name: ghcr.io cleanup action
        runs-on: ubuntu-latest
        permissions:
            packages: write
        steps:
            - uses: dataaxiom/ghcr-cleanup-action@v1
              with:
                  delete-untagged: true
